# DATA COMBINING

# biz turli hil joylardan turli hil formatdagi datalarni yigib oldik 
- API // - web scrapping// - CSV, EXCEL , MYSQL, POSTGRE SQL

# Data Combining - bu bir nechta datsetni birlashtirish

# data combining da asosan 2 xil usulda datalar birlashtiriladi
- Concat usuli 
- Merge

# Data Concat - bu dataframelarni ustma- ust yoki yonma yon qilib birlashtirish

In [1]:
# Vertical concat 

import pandas as pd 

df1 = pd.DataFrame({
    "name": ["Ali", "Gani"],
    "age": [25, 34]
})

df2 = pd.DataFrame({
    "name": ["Halima", "Salima"],
    "age": [15, 24]
})

df = pd.concat([df1, df2], axis=0)
print(df)

     name  age
0     Ali   25
1    Gani   34
0  Halima   15
1  Salima   24

In [2]:
# Horizontal concat 

import pandas as pd 

df1 = pd.DataFrame({
    "name": ["Ali", "Gani"],
    "age": [25, 34]
})

df2 = pd.DataFrame({
    "name": ["Halima", "Salima"],
    "age": [15, 24]
})

df = pd.concat([df1, df2], axis=1)
print(df)

   name  age    name  age
0   Ali   25  Halima   15
1  Gani   34  Salima   24

# Data Merging - bu datalarni umumiy ustunlar orqali birlashtirish

In [4]:
df3 = pd.DataFrame({
    "id": [1, 2],
    "name": ["Hamid", "Laylijon"]
})

df4 = pd.DataFrame({
    "id": [1, 2],
    "salary": [1500, 2555]
})


df = pd.merge(df3, df4, on="id")
print(df)

   id      name  salary
0   1     Hamid    1500
1   2  Laylijon    2555

# data mergingda bir nechta usullar mavjud 

- inner - faqat mos kelganlarni birlashtirish 
- left - chap tamonni birlashtirish 
- right - ong tamonni birlashtirish
- outer - hammasini birlashtirish

In [5]:
pd.merge(df3, df4, on="id", how="inner")
pd.merge(df3, df4, on="id", how="left")
pd.merge(df3, df4, on="id", how="right")
pd.merge(df3, df4, on="id", how="outer")

   id      name  salary
0   1     Hamid    1500
1   2  Laylijon    2555

# Real Datasetlarni birlashtirish

In [7]:
df_5 = pd.read_csv(r"C:\Users\Rasulbekk\Desktop\Practise\Data\ronaldo_2016.csv")
df_5.head()

,Competition,wettbewerb,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,LaLiga,29,25,6,4,-,-,2.544'
1,NaN,Champions League,13,12,6,1,-,-,1.200'
2,NaN,Club World Cup,2,4,-,-,-,-,202'
3,NaN,Copa del Rey,2,1,-,-,-,-,180'

In [12]:
df_5.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Competition  0 non-null      float64
 1   wettbewerb   4 non-null      str
 2   Unnamed: 2   4 non-null      int64
 3   Unnamed: 3   4 non-null      int64
 4   Unnamed: 4   4 non-null      str
 5   Unnamed: 5   4 non-null      str
 6   Unnamed: 6   4 non-null      str
 7   Unnamed: 7   4 non-null      str
 8   Unnamed: 8   4 non-null      str
dtypes: float64(1), int64(2), str(6)
memory usage: 504.0 bytes

In [8]:
df_6 = pd.read_csv(r"C:\Users\Rasulbekk\Desktop\Practise\Data\ronaldo_2017.csv")
df_6.head()

,Competition,wettbewerb,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,LaLiga,29,25,6,4,-,-,2.544'
1,NaN,Champions League,13,12,6,1,-,-,1.200'
2,NaN,Club World Cup,2,4,-,-,-,-,202'
3,NaN,Copa del Rey,2,1,-,-,-,-,180'

In [13]:
df_6.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Competition  0 non-null      float64
 1   wettbewerb   4 non-null      str
 2   Unnamed: 2   4 non-null      int64
 3   Unnamed: 3   4 non-null      int64
 4   Unnamed: 4   4 non-null      str
 5   Unnamed: 5   4 non-null      str
 6   Unnamed: 6   4 non-null      str
 7   Unnamed: 7   4 non-null      str
 8   Unnamed: 8   4 non-null      str
dtypes: float64(1), int64(2), str(6)
memory usage: 504.0 bytes

In [9]:
df_7 = pd.read_csv(r"C:\Users\Rasulbekk\Desktop\Practise\Data\ronaldo_2025.csv")
df_7.head()

,Competition,wettbewerb,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Saudi Pro League,3,3,-,-,-,-,270'
1,NaN,Saudi Super Cup,2,1,1,-,-,-,180'
2,NaN,King's Cup,-,-,-,-,-,-,-

In [14]:
df_7.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Competition  0 non-null      float64
 1   wettbewerb   3 non-null      str
 2   Unnamed: 2   3 non-null      str
 3   Unnamed: 3   3 non-null      str
 4   Unnamed: 4   3 non-null      str
 5   Unnamed: 5   3 non-null      str
 6   Unnamed: 6   3 non-null      str
 7   Unnamed: 7   3 non-null      str
 8   Unnamed: 8   3 non-null      str
dtypes: float64(1), str(8)
memory usage: 416.0 bytes

In [10]:
import pandas as pd 
from pathlib import Path 

base = Path(r"C:\Users\Rasulbekk\Desktop\Practise\Data") 

seasons = ["2016", "2017", "2025"] 

dfs = []

for s in seasons:
    file = base / f"ronaldo_{s}.csv"
    if not file.exists():
        print(f"File not found: {file}")
        continue
    df_temp = pd.read_csv(file)
    df_temp["season"] = s
    dfs.append(df_temp)


df_all = pd.concat(dfs, ignore_index=True)

print("Combined shape: ", df.shape)
print(df_all.head())

Combined shape:  (2, 3)
   Competition        wettbewerb Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0          NaN            LaLiga         29         25          6          4
1          NaN  Champions League         13         12          6          1
2          NaN    Club World Cup          2          4          -          -
3          NaN      Copa del Rey          2          1          -          -
4          NaN            LaLiga         29         25          6          4

  Unnamed: 6 Unnamed: 7 Unnamed: 8 season
0          -          -     2.544'   2016
1          -          -     1.200'   2016
2          -          -       202'   2016
3          -          -       180'   2016
4          -          -     2.544'   2017

In [11]:
df_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Competition  0 non-null      float64
 1   wettbewerb   11 non-null     str
 2   Unnamed: 2   11 non-null     object
 3   Unnamed: 3   11 non-null     object
 4   Unnamed: 4   11 non-null     str
 5   Unnamed: 5   11 non-null     str
 6   Unnamed: 6   11 non-null     str
 7   Unnamed: 7   11 non-null     str
 8   Unnamed: 8   11 non-null     str
 9   season       11 non-null     str
dtypes: float64(1), object(2), str(7)
memory usage: 1.3+ KB

In [15]:
df_all.to_csv(r"C:\Users\Rasulbekk\Desktop\Practise\Data\df_all.csv")